- name: Install pre-requisite packages
  yum: state=present name={{ item }}
  with_items:
    - curl
    - policycoreutils
    - postfix

- name: Set gitlab-ce repository
  yum_repository:
    baseurl: https://packages.gitlab.com/gitlab/gitlab-ce/el/6/$basearch
    enabled: yes
    file: gitlab_gitlab-ce
    gpgcheck: no
    gpgkey: https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
    metadata_expire: 300
    name: gitlab_gitlab-ce
    repo_gpgcheck: yes
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- name: Set gitlab-source repository
  yum_repository:
    baseurl: https://packages.gitlab.com/gitlab/gitlab-ce/el/6/SRPMS
    enabled: yes
    file: gitlab_gitlab-ce
    gpgcheck: no
    gpgkey: https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
    metadata_expire: 300
    name: gitlab_gitlab-ce-source
    repo_gpgcheck: yes
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- name: Install
  yum: state=present name="gitlab-ce-{{version}}"
  notify:
  - reconfigure

- name: Set gitlab hostname
  lineinfile: dest=/etc/gitlab/gitlab.rb regexp='^external_url' line='external_url \'{{hostname}}\''
  notify:
  - reconfigure